# Generated by Django 2.2.6 on 2019-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_app_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
    ]
