# Generated by Django 2.2.6 on 2019-10-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_app_login', '0002_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
