# Generated by Django 2.2.6 on 2019-10-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_app_login', '0003_auto_20191013_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
